services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev 
    env_file:
      .env
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app