# fly.toml app configuration file generated for backend-white-water-7735 on 2025-01-28T14:49:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-white-water-7735'
primary_region = 'lhr'

[build]


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
